### ISSUE TITLE
how to interpret the CHESS result

### ISSUE THREAD

**Issue by benxiahu** [vaquerizaslab/chess#15]
Hi,
    I have done chess analysis. I got some results:
_**correlation_dataframe_gained.csv
Elbow_index_gained.pdf
gained_features.tsv
subregions_3_clusters_gained.tsv
correlation_dataframe_lost.csv
Elbow_index_lost.pdf
lost_features.tsv
subregions_3_clusters_lost.tsv**_

How to explain and visualize those results?

**Comment by nickmachnik** [comment]
Hi,
we have an example analysis workflow in the [docs](https://chess-hic.readthedocs.io/en/latest/example_analysis.html).
You can find the code for the visualizations in there [here](https://github.com/vaquerizaslab/chess/blob/master/examples/dlbcl/example_analysis.ipynb).
Chess does not provide any functionality that is not documented there, every explanation and investigation of your results depends on your data and your question. 
Feel free to contact the Vaquerizas lab at https://www.vaquerizaslab.org/contact/ to inquire about a possible collaboration for the analysis of your data.
Best,
Nick
