### ISSUE TITLE
fanc.load error

### ISSUE THREAD

**Issue by benxiahu** [vaquerizaslab/chess#17]
Hi,
I used `patient_hic = fanc.load("case.cool")` to load cool Hi-C, and then run `patient_hic[region_string, region_string].data` to get data of interest.
However, I did not get any result.
do you know what is going on?
best,

**Comment by kaukrise** [comment]
Since this is the same issue you raised [here](https://github.com/vaquerizaslab/fanc/issues/30) I am closing this. Please avoid cross-posting.
