### ISSUE TITLE
Error while running "example analysis"

### ISSUE THREAD

**Issue by Gonysh** [vaquerizaslab/chess#19]
Hello,

I followed instructions for the example analysis but I keep getting an error.

Log:
> wget https://github.com/vaquerizaslab/chess/blob/master/examples/dlbcl/ukm_control_fixed_le_25kb_chr2.hic
> wget https://github.com/vaquerizaslab/chess/blob/master/examples/dlbcl/ukm_patient_fixed_le_25kb_chr2.hic
> chess pairs hg38 3000000 100000 ./hg38_chr2_3mb_win_100kb_step.bed --chromosome chr2
> chess sim ukm_control_fixed_le_25kb_chr2.hic ukm_patient_fixed_le_25kb_chr2.hic hg38_chr2_3mb_win_100kb_step.bed ukm_chr2_3mb_control_vs_patient_chess_results.tsv

2020-11-18 10:32:12,627 INFO CHESS version: 0.3.5
2020-11-18 10:32:12,627 INFO FAN-C version: 0.9.7
2020-11-18 10:32:12,631 INFO Loading reference contact data
2020-11-18 10:32:13,514 ERROR Regions file needs to bespecified for sparse input.
2020-11-18 10:32:13,515 ERROR Reference contact data could not be loaded. Please specify a valid input file. Files in sparse format can only be loaded if --reference-regions is specified.
File type not recognised (ukm_control_fixed_le_25kb_chr2.hic).

I assume the example analysis was supposed to work as is (referring to the "Reference contact data could not be loaded. Please specify a valid input file. Files in sparse format can only be loaded if --reference-regions is specified").
What do you think?

Thanks a lot,
Gony.

**Comment by kaukrise** [comment]
Hi, I think you are downloading the GitHub HTML page. Try this instead:

```
wget 'https://github.com/vaquerizaslab/chess/blob/master/examples/dlbcl/ukm_control_fixed_le_25kb_chr2.hic?raw=true'
wget 'https://github.com/vaquerizaslab/chess/blob/master/examples/dlbcl/ukm_patient_fixed_le_25kb_chr2.hic?raw=true'
```

**Comment by Gonysh** [comment]
Thank you very much.
It worked :).
