### ISSUE TITLE
Window size in base pairs

### ISSUE THREAD

**Issue by benxiahu** [vaquerizaslab/chess#2]
Hi,
   I want to scan the entire genome hg19, how do I set the window for Window size in base pairs and 
step for Step size in base pairs, respectively?

Best,

**Comment by nickmachnik** [comment]
Hey,
please have a look at the online documentation, specifically [here](https://chess-hic.readthedocs.io/en/latest/example_analysis.html#generating-a-pairs-input-file), the type of analysis you want to conduct is described with an example there.
Hope that helps!
Best,
Nick

**Comment by benxiahu** [comment]
thanks.
yes, I have checked it.
I want to analyze the enthire genome, not one chromosome.
so my question is how to set _window_ and _step_.

**Comment by nickmachnik** [comment]
For that, you simply don't set the `--chromosome` flag. That will give you windows for the whole genome. Window and Step are set with the respective positional arguments, as described in the [example](https://chess-hic.readthedocs.io/en/latest/example_analysis.html#generating-a-pairs-input-file) and in the [command line help](https://chess-hic.readthedocs.io/en/latest/cli.html#chess-pairs).

**Comment by benxiahu** [comment]
yeah. I do not set  the --_chromosome_. 
my question is how to set _Window_ and _Step_. 
Do you any suggestion to set _Window_ and _Step_?

**Comment by nickmachnik** [comment]
If you are asking what good values for _window_ and _step_ would be: that really depends on what you are looking for.
For the _window_,  I would in general say that it is advisable to run the analysis with a number of window sizes to catch different kinds of possible changes, but a good point to start may be 3 mb, as in the example.

_step_ should be greater or equal to the bin size of your data. If you want to scan the whole genome, it should also not exceed half the _window_ size. Within that range it really depends on your computational resources; the smaller the step, the more comparisons will be made, which increases the resolution of your scan. If your computational resources allow, you could start with a _step_ of 100 kb, as in the example.

**Comment by benxiahu** [comment]
thanks a lot.

when I ran sim command, I got this error:
AttributeError: 'Series' object has no attribute 'bias'.
the version of pandas is pandas-0.25.3.
do you think that the pandas should be degraded to pandas (0.22.0)?
best,

**Comment by nickmachnik** [comment]
Moved to a new issue thread. Will close, as the window size question seems answered.
