### ISSUE TITLE
The example hic file cannot be dumped

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/chess#21]
Dear all,

I found that the hic files cannot be dumped using juicer_tools. The command gives me following message. Any suggestion about visualing the example hic files will be appreciated.
`java -jar juicer_tools_1.22.01.jar dump observed NONE ukm_control_fixed_le_25kb_chr2.hic chr2 chr2 BP 10000 output`
WARN [2020-11-21T16:54:14,373]  [Globals.java:138] [main]  Development mode is enabled
Could not read hic file: null

Best wishes,
Zheng zhuqing

**Comment by nickmachnik** [comment]
Hi @biozzq ,
the example files are in FAN-C format, not Juicer. You can either visualize them with the FAN-C API [(here is the repo with a link to the docs)](https://github.com/vaquerizaslab/fanc) or convert the files to Juicer format with `fanc to-juicer`.

**Comment by biozzq** [comment]
Dear @nickmachnik 

Sorry, I found the command you provided just can convert a readpairs file to Juicer .hic format. Meanwhile, I cannot find any more usage instructions about the `fanc to-juicer` in the following link https://vaquerizaslab.github.io/fanc/getting_started.html. Please let me know if I missed anything.

fanc to-juicer -h
2020-11-21 22:44:44,526 INFO FAN-C version: 0.9.7
usage: fanc hic_to_juicer [-h] [--juicer-tools-jar JUICER_TOOLS_JAR_PATH] [-tmp] [-r RESOLUTIONS [RESOLUTIONS ...]] input [input ...] output

Convert a ReadPairs file to Juicer .hic format

positional arguments:
  input                 Input .pairs file(s), FAN-C format.
  output                Output Juicer file.

optional arguments:
  -h, --help            show this help message and exit
  --juicer-tools-jar JUICER_TOOLS_JAR_PATH
                        Path to juicer jar. You can also specify this in fanc.conf
  -tmp, --work-in-tmp   Work in temporary directory
  -r RESOLUTIONS [RESOLUTIONS ...], --resolutions RESOLUTIONS [RESOLUTIONS ...]
                        Resolutions in bp at which to "zoom" the juicer matrix.

Best wishes,
Zhuqing

**Comment by nickmachnik** [comment]
Hi @biozzq ,
sorry, you are right, you actually won't be able to convert the example files to juicer with that command, my bad.
There is a `fanc to-cooler` command that you could use to convert to cooler format, but I have no idea whether that is helpful at all. Maybe you could alternatively use fanc's [command line](https://fan-c.readthedocs.io/en/latest/fancplot.html) tools for plotting or its [python api](https://fan-c.readthedocs.io/en/latest/api/plot.html).

**Comment by biozzq** [comment]
Hi all,

I found that the fanc could be used to convert the valid pairs generated by HiC-Pro to hic format, and also do normalization and visualization. So I have changed to using fanc to generate the input for chess. Here, I am closing the issue, but feel free to reopen it.

Best wishes,
Zheng zhuqing
