### ISSUE TITLE
How to define the high confidence set of regions showing clear changes?

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/chess#26]
Dear all,

How to obtain the most different chromatin contact according to `chess sim` results. According to your Nature Genetics paper, I think that a lower z-ssim (the most import parameter) and higher SN (the second parameter) could represent the higher confidence. Is this right? Thank you very much.

Sincerely,
Zheng zhuqing

**Comment by nickmachnik** [comment]
Hi @biozzq ,
that is right, the regions with the clearest changes should be the ones with the lowest similarity (i.e. lowest z-ssim or ssim, that  should be the same), and highest SN.
Best,
Nick

**Comment by biozzq** [comment]
Hi @nickmachnik 
Thank you.
Best,
Zheng zhuqing
