### ISSUE TITLE
chess filter Unrecognized command 

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/chess#27]
Dear @nickmachnik 

I found that the filter command can not be recognized in the latest chess.

Best wishes,
Zheng zhuqing

**Comment by nickmachnik** [comment]
Hi @biozzq ,
that is right; the `filter` subcommand was removed, as it really was just doing some very simple csv parsing. Thanks for the info though, it seems that I forgot to remove it from the command line help.
Best,
Nick

**Comment by biozzq** [comment]
Thank you for your explaination.
