### ISSUE TITLE
BED / BEDPE file handling - BEDPE file produced by `chess pairs` is not 0-based

### ISSUE THREAD

**Issue by liz-is** [vaquerizaslab/chess#32]
Hello,

I was doing some manual processing of my CHESS results to figure out the best parameters for `chess extract` and noticed that the region coordinates returned by `chess.helpers.load_pairs_iter` don't match the coordinates given in the pairs file - e.g. the file contains a region "chr9:21900001-31900001", which is loaded as "chr9:21900002-31900001". This occurs because when converting the region into a `GenomicRegion` object, `chess.helpers.load_pairs_iter` [adds 1 to the start coordinate](https://github.com/vaquerizaslab/chess/blob/a9c6d13686195ed4470e5edf34929d25b0f37886/chess/helpers.py#L475). This makes sense because BED files, and by extension BEDPE files, are [0-based](https://genome.ucsc.edu/FAQ/FAQformat.html#format1).

Tracing this back through my file processing (because I've definitely made 0-based / 1-based coordinate conversion errors a bunch of times!), I realised that this comes from the original pairs BEDPE file that was generated with `chess pairs`, which returns pairs starting with e.g. `chr1    1       10000001        chr1    1       10000001        0       .       +       +`

This is of course a very minor issue that's not going to have any impact on actual results given that Hi-C data is binned at much lower resolution and CHESS runs on large genomic regions, but for consistency with other software and ease of handling, it would be nice if the BEDPE files were 0-based! :)

I would be happy to make the change and make a pull request if you are happy with that and it's easiest for you.

**Comment by nickmachnik** [comment]
Hi @liz-is,
thank you for reporting this! If you already know what needs to be changed and how, please go ahead and submit a pull request. Else, I will look into this one of the next days :)

**Comment by liz-is** [comment]
PR created! https://github.com/vaquerizaslab/chess/pull/33

**Comment by nickmachnik** [comment]
PR accepted, thank you Liz! I added a note to the changelog, this will be added pipy with the next release.
