### ISSUE TITLE
BEDPE file format

### ISSUE THREAD

**Issue by ysora** [vaquerizaslab/chess#37]
Hi, I am trying to run chess sim command.
In 'pairs' option, I tried to input hiccups output which is composed of 6 columns (chr1, start1, end1, chr2, start2, end2).
However, an error occurred saying  a file with 10 columns is expected. 
Could you let me know the exact file format for pairs option in chess sim command?
Thanks.

**Comment by liz-is** [comment]
Hello,

The input BEDPE file should correspond to the format as defined by [bedtools](https://bedtools.readthedocs.io/en/latest/content/general-usage.html). The "score" column is not used and can be a dummy value, but the other columns are required. I thought this was mentioned in the docs but I can't find it, so we can add it / make it more obvious!

However, as discussed in [another issue](https://github.com/vaquerizaslab/chess/issues/23#issuecomment-737339743), it sounds like you are trying to use off-diagonal regions as input to CHESS. Unfortunately this will not work properly, as CHESS was designed to work with and tested on regions along the diagonal. To compare loops between samples, you could create windows that include the whole span of the loop, or use a "genome scan" approach as described in the paper.

**Comment by liz-is** [comment]
Hello, I've now updated the [docs](https://chess-hic.readthedocs.io/en/latest/cli.html#chess-sim) and [FAQ](https://chess-hic.readthedocs.io/en/latest/faq.html#can-i-use-chess-to-compare-the-results-of-loop-calling-software-between-samples) to address both the expected BEDPE format and the use of off-diagonal regions as input. Do you have any follow up queries? If not, I'll close this issue.

**Comment by ysora** [comment]
Yes you can close the issue
Thanks

Sora

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
