### ISSUE TITLE
Get observed/expected from Juicer Hi-C

### ISSUE THREAD

**Issue by sshen82** [vaquerizaslab/chess#39]
Hi, is there a way to get observed/expected from Juicer Hi-C using fanc.load function?

**Comment by kaukrise** [comment]
CHESS will automatically use the O/E transformed values from the Juicer file, unless you specify `--oe-input`.

If you are asking about the FAN-C API you can do this:

```python
import fanc

hic = fanc.load("/path/to/juicer.hic@<resolution>")

region = '1:5mb-6mb'

# get normal matrix
m = hic.matrix((region, region))

# get O/E matrix
oe = hic.matrix((region, region), oe=True)
```

Please also look [here](https://fan-c.readthedocs.io/en/latest/api/interfaces/matrix_interface.html)

**Comment by sshen82** [comment]
Get it. Thank you!
