### ISSUE TITLE
speed up the chess run

### ISSUE THREAD

**Issue by zy041225** [vaquerizaslab/chess#51]
Dear all,

Thank you for providing this tool. But I'm wondering if it is possible to speed up the chess run. I'm suffering from the slow chess sim process. It takes more than 4 days to read a primate reference balanced cool file. The cool file is in 20Kb resolution generated from ~30X Hi-C reads, about 2Gb in size. Since I'm only interested in one particular chromosome, is it possible to generate a subset of the data as input for chess?

Many thanks

Best,
Yang

**Comment by liz-is** [comment]
Hello,
Yes, you can certainly use a Hi-C file that has been subsetted to only contain your chromosome of interest. You might also consider converting your .cool file to Juicer or FAN-C format, see here: https://chess-hic.readthedocs.io/en/latest/faq.html#why-is-chess-sim-so-slow
